
-- THIS DEMO SIMPLY SHOWS HOW TO USE THE STUFF FUNCTION TO INSERT A STRING
-- INTO ANOTHER STRING. BECAUSE THE FOURTH PARAMETER IS AN EMPTY STRING THIS
-- WILL REPLACE THE FIRST TWO CHARACTERS WITH AN EMPTY STRING. 


-- EXAMPLE PRIOR TO USING STUFF FUNCTION TO REMOVE THE COMMA AND SPACE AT THE BEGINNING.
USE AdventureWorks2016;

SELECT ', ' + psc.Name
			   FROM Production.ProductSubcategory psc 
			  FOR XML PATH('')


-- REMOVE THE COMMA AND SPACE WITH THE STUFF FUNCTION.
SELECT
	STUFF((SELECT ', ' + psc.Name
			   FROM Production.ProductSubcategory psc 
			  FOR XML PATH('')), 1, 2, '')	