-- DEMO 1 -- TRY_CAST & TRY_CONVERT
SELECT CAST('TEST' AS INT) TEST 
SELECT CONVERT(INT, 'TEST') TEST 

-- BOTH RETURN NULL
SELECT TRY_CAST('TEST' AS INT) TEST
SELECT TRY_CONVERT(INT, 'TEST') TEST

-- BOTH RETURN PROPER DATE
SELECT TRY_CAST('20150606' AS DATE) TEST
SELECT TRY_CONVERT(date, '20150606') TEST

-- BOTH FAIL Because this conversion is not allowed.
SELECT TRY_CAST(20150606 AS DATE) TEST
SELECT TRY_CONVERT(date, 20150606) TEST

-- USE INSIDE CASE STATEMENT FOR CONDITIONAL LOGIC.
SELECT 
    CASE WHEN TRY_CAST('2016-01-32' AS DATE) IS NULL 
    THEN 'Cast Failed'
    ELSE 'Cast Succeeded'
END AS Result;
GO

